export interface Career {
  id: string;
  title: string;
  icon: string;
  category: string;
  description: string;
  salary: string;
  education: string;
  skills: string[];
  nextSteps: string[];
  subjectMatch: string[];
  environmentMatch: string[];
  strengthsMatch: string[];
  motivationMatch: string[];
  personalityMatch: string[];
}

export const CAREERS: Career[] = [
  // ── Technology ────────────────────────────────────────────────────────────
  {
    id: "software-engineer",
    title: "Software Engineer",
    icon: "💻",
    category: "Technology",
    description: "Design, develop and maintain software systems, applications and platforms that power the modern world.",
    salary: "$100k – $180k",
    education: "Bachelor's Degree",
    skills: ["Programming", "Problem Solving", "System Design", "Debugging", "Algorithms"],
    nextSteps: ["Learn Python, JavaScript, or Java", "Build a GitHub portfolio", "Pursue a CS degree or coding bootcamp", "Apply for internships", "Contribute to open-source"],
    subjectMatch: ["Technology", "Science & Research", "Engineering"],
    environmentMatch: ["Remote/Home", "Office/Corporate", "Flexible/Hybrid"],
    strengthsMatch: ["Problem Solving", "Analytical Thinking", "Attention to Detail"],
    motivationMatch: ["Solving hard problems", "Building things", "Learning constantly"],
    personalityMatch: ["Independent Worker", "Detail-Oriented", "Team Player"],
  },
  {
    id: "data-scientist",
    title: "Data Scientist",
    icon: "📊",
    category: "Technology",
    description: "Extract insights from complex data using statistical models, machine learning, and visualization to guide business decisions.",
    salary: "$95k – $165k",
    education: "Master's or higher",
    skills: ["Python/R", "Statistics", "Machine Learning", "Data Visualization", "SQL"],
    nextSteps: ["Learn Python and statistics", "Complete data science courses", "Practice on Kaggle", "Build an analysis portfolio", "Pursue a graduate degree"],
    subjectMatch: ["Technology", "Science & Research", "Business & Finance"],
    environmentMatch: ["Remote/Home", "Office/Corporate", "Flexible/Hybrid"],
    strengthsMatch: ["Analytical Thinking", "Problem Solving", "Attention to Detail"],
    motivationMatch: ["Solving hard problems", "Learning constantly", "Making an impact"],
    personalityMatch: ["Independent Worker", "Detail-Oriented", "Adaptable/Flexible"],
  },
  {
    id: "cybersecurity-analyst",
    title: "Cybersecurity Analyst",
    icon: "🔒",
    category: "Technology",
    description: "Protect organizations from digital threats by monitoring networks, identifying vulnerabilities, and responding to security incidents.",
    salary: "$85k – $160k",
    education: "Bachelor's Degree",
    skills: ["Network Security", "Ethical Hacking", "SIEM Tools", "Risk Assessment", "Incident Response"],
    nextSteps: ["Study networking and Linux fundamentals", "Earn CompTIA Security+ certification", "Learn ethical hacking (CEH/OSCP)", "Practice on TryHackMe or HackTheBox", "Apply for SOC analyst roles"],
    subjectMatch: ["Technology", "Science & Research"],
    environmentMatch: ["Office/Corporate", "Remote/Home", "Flexible/Hybrid"],
    strengthsMatch: ["Analytical Thinking", "Attention to Detail", "Problem Solving"],
    motivationMatch: ["Solving hard problems", "Making an impact", "Learning constantly"],
    personalityMatch: ["Detail-Oriented", "Independent Worker", "Adaptable/Flexible"],
  },
  {
    id: "cloud-engineer",
    title: "Cloud Engineer",
    icon: "☁️",
    category: "Technology",
    description: "Design, build, and maintain cloud infrastructure on platforms like AWS, Azure, and GCP to power scalable applications.",
    salary: "$105k – $185k",
    education: "Bachelor's Degree",
    skills: ["AWS/Azure/GCP", "DevOps", "Kubernetes", "Terraform", "CI/CD"],
    nextSteps: ["Learn Linux and networking basics", "Get AWS/Azure certifications", "Practice infrastructure as code", "Build cloud projects", "Join DevOps communities"],
    subjectMatch: ["Technology", "Engineering"],
    environmentMatch: ["Remote/Home", "Office/Corporate", "Flexible/Hybrid"],
    strengthsMatch: ["Problem Solving", "Analytical Thinking", "Attention to Detail"],
    motivationMatch: ["Building things", "Solving hard problems", "Learning constantly"],
    personalityMatch: ["Independent Worker", "Detail-Oriented", "Adaptable/Flexible"],
  },
  {
    id: "ai-ml-engineer",
    title: "AI / ML Engineer",
    icon: "🤖",
    category: "Technology",
    description: "Build intelligent systems using machine learning, deep learning, and neural networks that can learn from data and make predictions.",
    salary: "$120k – $220k",
    education: "Master's or higher",
    skills: ["Deep Learning", "TensorFlow/PyTorch", "Python", "Model Deployment", "Data Engineering"],
    nextSteps: ["Master Python and linear algebra", "Study ML fundamentals (Coursera)", "Build projects using real datasets", "Publish on Kaggle", "Pursue a graduate degree or research role"],
    subjectMatch: ["Technology", "Science & Research"],
    environmentMatch: ["Remote/Home", "Office/Corporate", "Flexible/Hybrid"],
    strengthsMatch: ["Analytical Thinking", "Problem Solving", "Attention to Detail"],
    motivationMatch: ["Solving hard problems", "Building things", "Learning constantly"],
    personalityMatch: ["Independent Worker", "Detail-Oriented"],
  },
  {
    id: "product-manager",
    title: "Product Manager",
    icon: "📱",
    category: "Technology",
    description: "Drive product vision and strategy by bridging the gap between customers, business goals, and engineering teams.",
    salary: "$90k – $175k",
    education: "Bachelor's Degree",
    skills: ["Product Strategy", "User Research", "Agile/Scrum", "Data Analysis", "Stakeholder Management"],
    nextSteps: ["Study business and tech fundamentals", "Learn agile methodologies", "Build side projects or apps", "Earn a Product Management certification", "Transition from technical or business roles"],
    subjectMatch: ["Technology", "Business & Finance"],
    environmentMatch: ["Office/Corporate", "Flexible/Hybrid"],
    strengthsMatch: ["Leadership", "Communication", "Analytical Thinking"],
    motivationMatch: ["Building things", "Making an impact", "Solving hard problems"],
    personalityMatch: ["Leader", "Adaptable/Flexible", "Team Player"],
  },
  // ── Arts & Design ─────────────────────────────────────────────────────────
  {
    id: "ux-designer",
    title: "UX Designer",
    icon: "🎨",
    category: "Arts & Design",
    description: "Create intuitive, beautiful digital experiences by researching users and designing interfaces that are both functional and delightful.",
    salary: "$75k – $140k",
    education: "Bachelor's Degree",
    skills: ["User Research", "Wireframing", "Figma", "Prototyping", "Visual Design"],
    nextSteps: ["Learn Figma and Adobe XD", "Study human-computer interaction", "Build a portfolio of design projects", "Conduct usability studies", "Apply for junior UX roles"],
    subjectMatch: ["Arts & Design", "Technology", "Social Work"],
    environmentMatch: ["Office/Corporate", "Creative Studio", "Remote/Home", "Flexible/Hybrid"],
    strengthsMatch: ["Creativity", "Empathy", "Attention to Detail"],
    motivationMatch: ["Creative expression", "Helping others", "Building things"],
    personalityMatch: ["Team Player", "Adaptable/Flexible", "Detail-Oriented"],
  },
  {
    id: "graphic-designer",
    title: "Graphic Designer",
    icon: "✏️",
    category: "Arts & Design",
    description: "Communicate ideas visually through logos, illustrations, layouts, and branding for digital and print media.",
    salary: "$45k – $90k",
    education: "Associate Degree",
    skills: ["Adobe Creative Suite", "Typography", "Branding", "Illustration", "Color Theory"],
    nextSteps: ["Master Photoshop, Illustrator, InDesign", "Build a diverse design portfolio", "Freelance on Fiverr or Upwork", "Pursue a design degree", "Network with creative professionals"],
    subjectMatch: ["Arts & Design"],
    environmentMatch: ["Creative Studio", "Remote/Home", "Flexible/Hybrid"],
    strengthsMatch: ["Creativity", "Attention to Detail"],
    motivationMatch: ["Creative expression", "Building things"],
    personalityMatch: ["Independent Worker", "Adaptable/Flexible"],
  },
  {
    id: "content-creator",
    title: "Content Creator",
    icon: "🎬",
    category: "Arts & Design",
    description: "Produce engaging videos, articles, podcasts, or social media content that entertains, educates, or inspires audiences online.",
    salary: "$30k – $200k+",
    education: "High School only",
    skills: ["Video Editing", "Storytelling", "Social Media", "Photography", "Audience Engagement"],
    nextSteps: ["Choose your niche and format", "Learn video editing basics", "Start creating consistently", "Grow your audience on one platform first", "Monetize through ads or sponsorships"],
    subjectMatch: ["Arts & Design", "Technology", "Education"],
    environmentMatch: ["Remote/Home", "Creative Studio", "Flexible/Hybrid"],
    strengthsMatch: ["Creativity", "Communication"],
    motivationMatch: ["Creative expression", "Making money"],
    personalityMatch: ["Independent Worker", "Adaptable/Flexible"],
  },
  {
    id: "architect",
    title: "Architect",
    icon: "🏛️",
    category: "Arts & Design",
    description: "Design functional, safe, and aesthetically beautiful buildings and spaces that shape how people live, work, and move through the world.",
    salary: "$70k – $140k",
    education: "Master's or higher",
    skills: ["AutoCAD", "3D Modeling", "Structural Knowledge", "Design Theory", "Project Management"],
    nextSteps: ["Study architecture at an accredited university", "Complete internship (IDP hours)", "Pass the Architecture Registration Exam (ARE)", "Specialize in residential, commercial, or urban design", "Build a portfolio of design work"],
    subjectMatch: ["Arts & Design", "Engineering", "Science & Research"],
    environmentMatch: ["Office/Corporate", "Creative Studio", "Outdoors/Field"],
    strengthsMatch: ["Creativity", "Attention to Detail", "Analytical Thinking"],
    motivationMatch: ["Creative expression", "Building things", "Making an impact"],
    personalityMatch: ["Detail-Oriented", "Independent Worker", "Leader"],
  },
  {
    id: "animator",
    title: "Animator / Motion Designer",
    icon: "🎞️",
    category: "Arts & Design",
    description: "Bring stories and ideas to life through 2D or 3D animation, motion graphics, and visual effects for film, games, or digital media.",
    salary: "$50k – $120k",
    education: "Bachelor's Degree",
    skills: ["After Effects", "Blender/Maya", "Storytelling", "Keyframing", "Visual Composition"],
    nextSteps: ["Learn After Effects and Blender", "Study animation principles", "Build a showreel/portfolio", "Work on short films or freelance projects", "Apply to studios or agencies"],
    subjectMatch: ["Arts & Design", "Technology"],
    environmentMatch: ["Creative Studio", "Remote/Home", "Flexible/Hybrid"],
    strengthsMatch: ["Creativity", "Attention to Detail"],
    motivationMatch: ["Creative expression", "Building things"],
    personalityMatch: ["Independent Worker", "Detail-Oriented"],
  },
  // ── Business & Finance ───────────────────────────────────────────────────
  {
    id: "financial-analyst",
    title: "Financial Analyst",
    icon: "💰",
    category: "Business & Finance",
    description: "Analyze financial data, market trends, and investment opportunities to guide business decisions and maximize returns.",
    salary: "$65k – $130k",
    education: "Bachelor's Degree",
    skills: ["Excel/Financial Modeling", "Accounting", "Market Analysis", "Forecasting", "Reporting"],
    nextSteps: ["Study finance, accounting, or economics", "Learn Excel and financial modeling", "Pursue CFA or CPA certification", "Intern at banks or investment firms", "Network through finance associations"],
    subjectMatch: ["Business & Finance", "Science & Research"],
    environmentMatch: ["Office/Corporate", "Flexible/Hybrid"],
    strengthsMatch: ["Analytical Thinking", "Attention to Detail", "Problem Solving"],
    motivationMatch: ["Making money", "Solving hard problems", "Learning constantly"],
    personalityMatch: ["Detail-Oriented", "Independent Worker", "Adaptable/Flexible"],
  },
  {
    id: "entrepreneur",
    title: "Entrepreneur",
    icon: "🚀",
    category: "Business & Finance",
    description: "Build and lead your own business ventures, turning innovative ideas into products or services that create real value.",
    salary: "Variable / Unlimited",
    education: "Any level",
    skills: ["Leadership", "Risk Management", "Networking", "Product Development", "Sales"],
    nextSteps: ["Identify a problem you're passionate about", "Research your target market", "Build an MVP", "Seek mentors and startup communities", "Apply for accelerators or funding"],
    subjectMatch: ["Business & Finance", "Technology", "Arts & Design"],
    environmentMatch: ["Remote/Home", "Flexible/Hybrid", "Office/Corporate"],
    strengthsMatch: ["Leadership", "Problem Solving", "Creativity"],
    motivationMatch: ["Making money", "Building things", "Making an impact"],
    personalityMatch: ["Leader", "Adaptable/Flexible"],
  },
  {
    id: "marketing-manager",
    title: "Marketing Manager",
    icon: "📣",
    category: "Business & Finance",
    description: "Develop and execute marketing strategies to build brand awareness, attract customers, and drive business growth.",
    salary: "$60k – $130k",
    education: "Bachelor's Degree",
    skills: ["Campaign Strategy", "Digital Marketing", "Analytics", "Content Creation", "Brand Management"],
    nextSteps: ["Study marketing, communications, or business", "Learn digital marketing (SEO, social media)", "Earn Google Analytics or HubSpot certifications", "Build a portfolio of campaigns", "Start with coordinator roles"],
    subjectMatch: ["Business & Finance", "Arts & Design", "Technology"],
    environmentMatch: ["Office/Corporate", "Remote/Home", "Flexible/Hybrid"],
    strengthsMatch: ["Creativity", "Communication", "Analytical Thinking"],
    motivationMatch: ["Creative expression", "Making money", "Making an impact"],
    personalityMatch: ["Leader", "Team Player", "Adaptable/Flexible"],
  },
  {
    id: "accountant",
    title: "Accountant / CPA",
    icon: "🧾",
    category: "Business & Finance",
    description: "Manage financial records, prepare tax documents, and ensure organizations remain financially healthy and compliant with regulations.",
    salary: "$55k – $110k",
    education: "Bachelor's Degree",
    skills: ["Bookkeeping", "Tax Law", "Financial Reporting", "Auditing", "Excel"],
    nextSteps: ["Study accounting or finance", "Pass the CPA exam", "Gain experience at a public accounting firm", "Specialize in tax, audit, or forensic accounting", "Join the AICPA"],
    subjectMatch: ["Business & Finance"],
    environmentMatch: ["Office/Corporate", "Remote/Home", "Flexible/Hybrid"],
    strengthsMatch: ["Attention to Detail", "Analytical Thinking"],
    motivationMatch: ["Making money", "Solving hard problems"],
    personalityMatch: ["Detail-Oriented", "Independent Worker"],
  },
  {
    id: "hr-manager",
    title: "HR Manager",
    icon: "👥",
    category: "Business & Finance",
    description: "Attract, develop, and retain talent while fostering a positive workplace culture and handling employee relations and compliance.",
    salary: "$55k – $115k",
    education: "Bachelor's Degree",
    skills: ["Recruitment", "Employee Relations", "Labor Law", "Training & Development", "Conflict Resolution"],
    nextSteps: ["Study human resources or business", "Earn PHR or SHRM certification", "Gain HR coordinator experience", "Learn HRIS systems", "Specialize in talent acquisition or L&D"],
    subjectMatch: ["Business & Finance", "Social Work", "Education"],
    environmentMatch: ["Office/Corporate", "Flexible/Hybrid"],
    strengthsMatch: ["Communication", "Empathy", "Leadership"],
    motivationMatch: ["Helping others", "Making an impact"],
    personalityMatch: ["Leader", "Team Player", "Adaptable/Flexible"],
  },
  // ── Healthcare ────────────────────────────────────────────────────────────
  {
    id: "doctor",
    title: "Medical Doctor",
    icon: "🏥",
    category: "Healthcare",
    description: "Diagnose and treat illnesses, injuries, and conditions to improve and maintain patient health across all ages.",
    salary: "$200k – $400k+",
    education: "Master's or higher",
    skills: ["Clinical Diagnosis", "Patient Care", "Medical Knowledge", "Communication", "Decision Making"],
    nextSteps: ["Excel in science subjects", "Complete a pre-med undergraduate degree", "Score well on the MCAT", "Attend medical school (4 years)", "Complete residency (3–7 years)"],
    subjectMatch: ["Healthcare", "Science & Research"],
    environmentMatch: ["Hospital/Lab"],
    strengthsMatch: ["Problem Solving", "Empathy", "Attention to Detail"],
    motivationMatch: ["Helping others", "Making an impact", "Learning constantly"],
    personalityMatch: ["Leader", "Detail-Oriented", "Adaptable/Flexible"],
  },
  {
    id: "nurse",
    title: "Registered Nurse",
    icon: "💊",
    category: "Healthcare",
    description: "Provide direct patient care, administer medications, and coordinate with physicians to ensure patient wellbeing and recovery.",
    salary: "$60k – $110k",
    education: "Bachelor's Degree",
    skills: ["Patient Care", "Medical Procedures", "Communication", "Critical Thinking", "Compassion"],
    nextSteps: ["Complete a nursing degree (BSN)", "Pass the NCLEX-RN exam", "Gain clinical experience", "Choose a specialization", "Pursue advanced nursing certifications"],
    subjectMatch: ["Healthcare", "Social Work"],
    environmentMatch: ["Hospital/Lab"],
    strengthsMatch: ["Empathy", "Attention to Detail", "Communication"],
    motivationMatch: ["Helping others", "Making an impact"],
    personalityMatch: ["Team Player", "Adaptable/Flexible", "Detail-Oriented"],
  },
  {
    id: "psychologist",
    title: "Psychologist",
    icon: "🧠",
    category: "Healthcare",
    description: "Study human behavior and mental processes to help individuals overcome challenges, improve wellbeing, and achieve their goals.",
    salary: "$75k – $140k",
    education: "Master's or higher",
    skills: ["Active Listening", "Empathy", "Assessment", "Therapy Techniques", "Research"],
    nextSteps: ["Study psychology as undergraduate", "Pursue a master's or doctoral degree", "Complete supervised clinical hours", "Pass state licensing exams", "Choose a specialization"],
    subjectMatch: ["Healthcare", "Social Work", "Science & Research"],
    environmentMatch: ["Office/Corporate", "Hospital/Lab", "Flexible/Hybrid"],
    strengthsMatch: ["Empathy", "Communication", "Analytical Thinking"],
    motivationMatch: ["Helping others", "Making an impact", "Learning constantly"],
    personalityMatch: ["Team Player", "Adaptable/Flexible", "Independent Worker"],
  },
  {
    id: "pharmacist",
    title: "Pharmacist",
    icon: "💉",
    category: "Healthcare",
    description: "Dispense medications, counsel patients on drug interactions, and work with healthcare teams to optimize treatment plans.",
    salary: "$120k – $160k",
    education: "Master's or higher",
    skills: ["Pharmacology", "Patient Counseling", "Drug Interactions", "Clinical Knowledge", "Attention to Detail"],
    nextSteps: ["Earn a PharmD degree (4 years)", "Complete pharmacy residency", "Pass NAPLEX and MPJE exams", "Get state pharmacy license", "Specialize in clinical or retail pharmacy"],
    subjectMatch: ["Healthcare", "Science & Research"],
    environmentMatch: ["Hospital/Lab", "Office/Corporate"],
    strengthsMatch: ["Attention to Detail", "Empathy", "Analytical Thinking"],
    motivationMatch: ["Helping others", "Making an impact", "Learning constantly"],
    personalityMatch: ["Detail-Oriented", "Team Player"],
  },
  {
    id: "physical-therapist",
    title: "Physical Therapist",
    icon: "🏃",
    category: "Healthcare",
    description: "Help patients recover from injuries, surgeries, and chronic conditions by developing personalized rehabilitation programs.",
    salary: "$75k – $110k",
    education: "Master's or higher",
    skills: ["Anatomy", "Exercise Science", "Patient Assessment", "Rehabilitation", "Communication"],
    nextSteps: ["Study biology or kinesiology", "Earn a Doctor of Physical Therapy (DPT) degree", "Pass the NPTE licensing exam", "Complete clinical rotations", "Specialize in sports, neuro, or ortho PT"],
    subjectMatch: ["Healthcare", "Science & Research"],
    environmentMatch: ["Hospital/Lab", "Office/Corporate", "Outdoors/Field"],
    strengthsMatch: ["Empathy", "Communication", "Physical Dexterity"],
    motivationMatch: ["Helping others", "Making an impact"],
    personalityMatch: ["Team Player", "Adaptable/Flexible"],
  },
  {
    id: "dentist",
    title: "Dentist",
    icon: "🦷",
    category: "Healthcare",
    description: "Diagnose and treat oral health issues, perform dental procedures, and help patients maintain healthy teeth and gums.",
    salary: "$150k – $250k",
    education: "Master's or higher",
    skills: ["Dental Procedures", "Patient Care", "Oral Anatomy", "X-ray Interpretation", "Hand Dexterity"],
    nextSteps: ["Complete a pre-dental undergraduate degree", "Score well on the DAT", "Attend dental school (4 years)", "Pass national dental board exams", "Open a practice or join a group practice"],
    subjectMatch: ["Healthcare", "Science & Research"],
    environmentMatch: ["Hospital/Lab", "Office/Corporate"],
    strengthsMatch: ["Physical Dexterity", "Attention to Detail", "Empathy"],
    motivationMatch: ["Helping others", "Making money", "Making an impact"],
    personalityMatch: ["Detail-Oriented", "Independent Worker"],
  },
  // ── Education ─────────────────────────────────────────────────────────────
  {
    id: "teacher",
    title: "Teacher / Educator",
    icon: "📚",
    category: "Education",
    description: "Inspire and educate students by creating engaging lessons that build knowledge, critical thinking, and lifelong learning habits.",
    salary: "$40k – $75k",
    education: "Bachelor's Degree",
    skills: ["Communication", "Curriculum Design", "Patience", "Classroom Management", "Subject Expertise"],
    nextSteps: ["Choose a subject area or grade level", "Complete a teaching degree", "Earn a teaching license", "Complete student teaching practicum", "Apply for teaching positions"],
    subjectMatch: ["Education", "Social Work", "Science & Research"],
    environmentMatch: ["Office/Corporate", "Flexible/Hybrid"],
    strengthsMatch: ["Communication", "Empathy", "Leadership"],
    motivationMatch: ["Helping others", "Making an impact", "Learning constantly"],
    personalityMatch: ["Leader", "Team Player", "Adaptable/Flexible"],
  },
  {
    id: "school-counselor",
    title: "School Counselor",
    icon: "🎓",
    category: "Education",
    description: "Support students' academic, social-emotional, and career development to help them reach their full potential.",
    salary: "$50k – $85k",
    education: "Master's or higher",
    skills: ["Active Listening", "Crisis Intervention", "Career Advising", "Empathy", "Communication"],
    nextSteps: ["Study education or counseling", "Earn a master's in school counseling", "Complete supervised internship hours", "Get state counseling license", "Apply to K-12 school districts"],
    subjectMatch: ["Education", "Social Work", "Healthcare"],
    environmentMatch: ["Office/Corporate"],
    strengthsMatch: ["Empathy", "Communication", "Leadership"],
    motivationMatch: ["Helping others", "Making an impact"],
    personalityMatch: ["Team Player", "Adaptable/Flexible"],
  },
  {
    id: "librarian",
    title: "Librarian / Information Specialist",
    icon: "📖",
    category: "Education",
    description: "Curate, organize, and provide access to information resources while promoting literacy and lifelong learning in communities.",
    salary: "$50k – $80k",
    education: "Master's or higher",
    skills: ["Information Management", "Research", "Cataloging", "Technology", "Community Engagement"],
    nextSteps: ["Earn a degree in library science (MLS/MLIS)", "Gain experience in libraries or archives", "Learn information management systems", "Get state librarian certification", "Specialize in academic, public, or special libraries"],
    subjectMatch: ["Education", "Science & Research"],
    environmentMatch: ["Office/Corporate"],
    strengthsMatch: ["Attention to Detail", "Communication", "Analytical Thinking"],
    motivationMatch: ["Helping others", "Learning constantly"],
    personalityMatch: ["Detail-Oriented", "Independent Worker"],
  },
  // ── Engineering ───────────────────────────────────────────────────────────
  {
    id: "civil-engineer",
    title: "Civil Engineer",
    icon: "🏗️",
    category: "Engineering",
    description: "Design, plan, and oversee the construction of infrastructure like roads, bridges, buildings, and water systems.",
    salary: "$70k – $130k",
    education: "Bachelor's Degree",
    skills: ["AutoCAD", "Structural Analysis", "Project Management", "Mathematics", "Problem Solving"],
    nextSteps: ["Study civil engineering at university", "Complete engineering internships", "Pass the FE exam", "Gain PE license experience", "Specialize in structural or environmental engineering"],
    subjectMatch: ["Engineering", "Science & Research"],
    environmentMatch: ["Outdoors/Field", "Office/Corporate"],
    strengthsMatch: ["Problem Solving", "Analytical Thinking", "Attention to Detail"],
    motivationMatch: ["Building things", "Solving hard problems", "Making an impact"],
    personalityMatch: ["Detail-Oriented", "Team Player", "Leader"],
  },
  {
    id: "mechanical-engineer",
    title: "Mechanical Engineer",
    icon: "⚙️",
    category: "Engineering",
    description: "Design and develop mechanical systems and devices — from engines and turbines to medical devices and robotics.",
    salary: "$75k – $135k",
    education: "Bachelor's Degree",
    skills: ["CAD/CAM", "Thermodynamics", "Materials Science", "Manufacturing", "Problem Solving"],
    nextSteps: ["Study mechanical engineering", "Learn CAD tools (SolidWorks, AutoCAD)", "Complete internships at manufacturing firms", "Pass the FE exam", "Pursue PE licensure"],
    subjectMatch: ["Engineering", "Science & Research"],
    environmentMatch: ["Office/Corporate", "Outdoors/Field"],
    strengthsMatch: ["Problem Solving", "Analytical Thinking", "Physical Dexterity"],
    motivationMatch: ["Building things", "Solving hard problems"],
    personalityMatch: ["Detail-Oriented", "Team Player"],
  },
  {
    id: "electrician",
    title: "Electrician",
    icon: "⚡",
    category: "Engineering",
    description: "Install, maintain, and repair electrical systems in homes, businesses, and industrial facilities.",
    salary: "$50k – $100k",
    education: "Trade/Vocational",
    skills: ["Electrical Systems", "Blueprint Reading", "Troubleshooting", "Safety Protocols", "Physical Dexterity"],
    nextSteps: ["Complete an electrician vocational program", "Start an apprenticeship (4–5 years)", "Pass the journeyman electrician exam", "Gain varied electrical work experience", "Earn master electrician license"],
    subjectMatch: ["Engineering", "Science & Research"],
    environmentMatch: ["Outdoors/Field", "Office/Corporate"],
    strengthsMatch: ["Physical Dexterity", "Problem Solving", "Attention to Detail"],
    motivationMatch: ["Building things", "Making money"],
    personalityMatch: ["Independent Worker", "Detail-Oriented", "Adaptable/Flexible"],
  },
  {
    id: "aerospace-engineer",
    title: "Aerospace Engineer",
    icon: "🚀",
    category: "Engineering",
    description: "Design and develop aircraft, spacecraft, satellites, and missiles, working at the cutting edge of human exploration and aviation.",
    salary: "$90k – $165k",
    education: "Bachelor's Degree",
    skills: ["Aerodynamics", "CAD", "Propulsion", "Structural Analysis", "Systems Engineering"],
    nextSteps: ["Study aerospace or mechanical engineering", "Intern at aerospace companies (NASA, Boeing, SpaceX)", "Pass the FE exam", "Specialize in avionics, propulsion, or structures", "Pursue a graduate degree for research roles"],
    subjectMatch: ["Engineering", "Science & Research", "Technology"],
    environmentMatch: ["Office/Corporate", "Outdoors/Field"],
    strengthsMatch: ["Analytical Thinking", "Problem Solving", "Attention to Detail"],
    motivationMatch: ["Building things", "Solving hard problems", "Making an impact"],
    personalityMatch: ["Detail-Oriented", "Team Player"],
  },
  {
    id: "biomedical-engineer",
    title: "Biomedical Engineer",
    icon: "🧬",
    category: "Engineering",
    description: "Combine engineering principles with medical and biological sciences to design equipment, devices, and software for healthcare.",
    salary: "$75k – $140k",
    education: "Bachelor's Degree",
    skills: ["Biomechanics", "Medical Imaging", "CAD", "Regulatory Compliance", "Data Analysis"],
    nextSteps: ["Study biomedical or bioengineering", "Intern at medical device companies", "Learn FDA regulatory requirements", "Build interdisciplinary skills in biology and engineering", "Pursue a graduate degree for R&D roles"],
    subjectMatch: ["Engineering", "Healthcare", "Science & Research"],
    environmentMatch: ["Hospital/Lab", "Office/Corporate"],
    strengthsMatch: ["Problem Solving", "Analytical Thinking", "Attention to Detail"],
    motivationMatch: ["Helping others", "Building things", "Making an impact"],
    personalityMatch: ["Detail-Oriented", "Team Player"],
  },
  // ── Science & Research ────────────────────────────────────────────────────
  {
    id: "researcher",
    title: "Research Scientist",
    icon: "🔬",
    category: "Science & Research",
    description: "Conduct systematic investigations to expand scientific knowledge, develop new technologies, or solve complex real-world problems.",
    salary: "$65k – $140k",
    education: "Master's or higher",
    skills: ["Research Methodology", "Data Analysis", "Lab Techniques", "Scientific Writing", "Critical Thinking"],
    nextSteps: ["Excel in science and math", "Pursue an undergraduate research degree", "Gain lab experience through internships", "Complete a graduate degree (MS or PhD)", "Publish research and build academic profile"],
    subjectMatch: ["Science & Research", "Technology", "Healthcare"],
    environmentMatch: ["Hospital/Lab", "Office/Corporate"],
    strengthsMatch: ["Analytical Thinking", "Attention to Detail", "Problem Solving"],
    motivationMatch: ["Learning constantly", "Solving hard problems", "Making an impact"],
    personalityMatch: ["Independent Worker", "Detail-Oriented"],
  },
  {
    id: "environmental-scientist",
    title: "Environmental Scientist",
    icon: "🌿",
    category: "Science & Research",
    description: "Study the environment and develop solutions to environmental problems including pollution, climate change, and resource conservation.",
    salary: "$55k – $110k",
    education: "Bachelor's Degree",
    skills: ["Environmental Monitoring", "GIS", "Data Collection", "Policy Analysis", "Report Writing"],
    nextSteps: ["Study environmental science or ecology", "Gain field research experience", "Learn GIS and data analysis tools", "Work with environmental agencies or NGOs", "Pursue graduate studies for specialized roles"],
    subjectMatch: ["Science & Research", "Social Work"],
    environmentMatch: ["Outdoors/Field", "Office/Corporate"],
    strengthsMatch: ["Analytical Thinking", "Attention to Detail", "Problem Solving"],
    motivationMatch: ["Making an impact", "Learning constantly", "Helping others"],
    personalityMatch: ["Adaptable/Flexible", "Independent Worker"],
  },
  // ── Social Work ───────────────────────────────────────────────────────────
  {
    id: "social-worker",
    title: "Social Worker",
    icon: "🤝",
    category: "Social Work",
    description: "Support vulnerable individuals and communities by connecting them with resources, advocacy, and counseling services.",
    salary: "$40k – $75k",
    education: "Bachelor's Degree",
    skills: ["Empathy", "Case Management", "Crisis Intervention", "Advocacy", "Communication"],
    nextSteps: ["Earn a BSW or MSW degree", "Complete supervised field placements", "Obtain state social work license", "Specialize in child welfare, mental health, or medical", "Join the National Association of Social Workers"],
    subjectMatch: ["Social Work", "Education", "Healthcare"],
    environmentMatch: ["Office/Corporate", "Outdoors/Field", "Hospital/Lab"],
    strengthsMatch: ["Empathy", "Communication", "Leadership"],
    motivationMatch: ["Helping others", "Making an impact"],
    personalityMatch: ["Team Player", "Adaptable/Flexible"],
  },
  {
    id: "nonprofit-manager",
    title: "Nonprofit Manager",
    icon: "🌍",
    category: "Social Work",
    description: "Lead nonprofit organizations to deliver mission-driven programs, manage fundraising, and create lasting positive impact in communities.",
    salary: "$45k – $90k",
    education: "Bachelor's Degree",
    skills: ["Fundraising", "Grant Writing", "Program Management", "Community Outreach", "Leadership"],
    nextSteps: ["Volunteer with nonprofits to gain experience", "Study public administration or nonprofit management", "Learn grant writing and fundraising strategies", "Build relationships with donors and stakeholders", "Pursue MPA or MBA for leadership roles"],
    subjectMatch: ["Social Work", "Business & Finance", "Education"],
    environmentMatch: ["Office/Corporate", "Outdoors/Field", "Flexible/Hybrid"],
    strengthsMatch: ["Leadership", "Communication", "Empathy"],
    motivationMatch: ["Making an impact", "Helping others"],
    personalityMatch: ["Leader", "Team Player", "Adaptable/Flexible"],
  },
  // ── Skilled Trades ────────────────────────────────────────────────────────
  {
    id: "plumber",
    title: "Plumber",
    icon: "🔧",
    category: "Engineering",
    description: "Install, repair, and maintain water supply and drainage systems in residential, commercial, and industrial buildings.",
    salary: "$55k – $100k",
    education: "Trade/Vocational",
    skills: ["Pipe Fitting", "Blueprint Reading", "Problem Solving", "Physical Dexterity", "Safety"],
    nextSteps: ["Complete a plumbing vocational program", "Start an apprenticeship (4–5 years)", "Pass the journeyman plumber exam", "Gain diverse work experience", "Earn master plumber license"],
    subjectMatch: ["Engineering"],
    environmentMatch: ["Outdoors/Field", "Office/Corporate"],
    strengthsMatch: ["Physical Dexterity", "Problem Solving", "Attention to Detail"],
    motivationMatch: ["Building things", "Making money"],
    personalityMatch: ["Independent Worker", "Adaptable/Flexible"],
  },
  // ── Law & Justice ─────────────────────────────────────────────────────────
  {
    id: "lawyer",
    title: "Lawyer / Attorney",
    icon: "⚖️",
    category: "Business & Finance",
    description: "Advise clients on legal matters, represent them in court, and navigate complex laws to protect their rights and interests.",
    salary: "$75k – $250k+",
    education: "Master's or higher",
    skills: ["Legal Research", "Argumentation", "Writing", "Negotiation", "Critical Thinking"],
    nextSteps: ["Complete a bachelor's degree", "Score well on the LSAT", "Attend law school (3 years)", "Pass the bar exam", "Specialize in corporate, criminal, family, or IP law"],
    subjectMatch: ["Business & Finance", "Social Work", "Education"],
    environmentMatch: ["Office/Corporate", "Flexible/Hybrid"],
    strengthsMatch: ["Communication", "Analytical Thinking", "Attention to Detail"],
    motivationMatch: ["Making money", "Helping others", "Making an impact"],
    personalityMatch: ["Leader", "Independent Worker", "Detail-Oriented"],
  },
];

export const CATEGORIES = [...new Set(CAREERS.map(c => c.category))].sort();

export interface QuizAnswers {
  subjects: string | null;
  environment: string | null;
  strengths: string[];
  motivation: string | null;
  education: string | null;
  personality: string | null;
}

export interface CareerMatch {
  career: Career;
  score: number;
  percentage: number;
  matchReasons: string[];
}

export function calculateMatches(answers: QuizAnswers): CareerMatch[] {
  const results: CareerMatch[] = CAREERS.map(career => {
    let score = 0;
    const matchReasons: string[] = [];

    if (answers.subjects && career.subjectMatch.includes(answers.subjects)) {
      score += 30;
      matchReasons.push(`Aligns with your interest in ${answers.subjects}`);
    }
    if (answers.environment && career.environmentMatch.includes(answers.environment)) {
      score += 20;
      matchReasons.push(`Fits your preferred ${answers.environment} work environment`);
    }
    const strengthHits = answers.strengths.filter(s => career.strengthsMatch.includes(s));
    if (strengthHits.length > 0) {
      score += strengthHits.length * 15;
      matchReasons.push(`Uses your strength in ${strengthHits.slice(0, 2).join(" and ")}`);
    }
    if (answers.motivation && career.motivationMatch.includes(answers.motivation)) {
      score += 20;
      matchReasons.push(`Matches your motivation to "${answers.motivation.toLowerCase()}"`);
    }
    if (answers.education) {
      const eduMap: Record<string, number> = {
        "High School only": 1, "Trade/Vocational": 2, "Associate Degree": 3,
        "Bachelor's Degree": 4, "Master's or higher": 5,
      };
      const userEdu = eduMap[answers.education] || 0;
      const careerEdu = eduMap[career.education] || 6;
      if (userEdu >= careerEdu) {
        score += 10;
        if (userEdu === careerEdu) matchReasons.push("Matches your education level exactly");
      }
    }
    if (answers.personality && career.personalityMatch.includes(answers.personality)) {
      score += 15;
      matchReasons.push(`Suits your ${answers.personality.toLowerCase()} work style`);
    }

    const maxScore = 30 + 20 + 45 + 20 + 10 + 15;
    const percentage = Math.min(99, Math.round((score / maxScore) * 100));
    return { career, score, percentage, matchReasons: matchReasons.slice(0, 4) };
  });

  return results.sort((a, b) => b.score - a.score);
}
